In [1]:
cd ..

d:\school\aai\personalgit\aai-jik-huijberts\python


In [2]:
from utils.matrix_helper import MatrixHelper
import numpy as np
m_helper = MatrixHelper()

In [3]:
a = [[1,2,3],[4,5,6]]
b = [[1,1,1,1],[1,1,1,1],[1,1,1,1]]

print(m_helper.matMul(a,b))

[[6, 6, 6, 6], [15, 15, 15, 15]]


![./test_image.jpg](./test_image.jpg)

In [4]:
a_1 = [[3,4,2]]
b_1 = [[13,9,7,15],[8,7,4,6],[6,4,0,3]]
print(m_helper.matMul(a_1,b_1))

[[83, 63, 37, 75]]


In [5]:
identifier = m_helper.idMat(5)
for row in identifier:
    print(row)

[1, 0, 0, 0, 0]
[0, 1, 0, 0, 0]
[0, 0, 1, 0, 0]
[0, 0, 0, 1, 0]
[0, 0, 0, 0, 1]


In [6]:
helper_array = [[13,9,7],[8,7,4],[6,4,0]]
inverted = m_helper.invMat([[13,9,7],[8,7,4],[6,4,0]])
print(np.linalg.inv(helper_array))
for row in inverted:
    print(row)

[[ 0.25806452 -0.4516129   0.20967742]
 [-0.38709677  0.67741935 -0.06451613]
 [ 0.16129032 -0.03225806 -0.30645161]]
[0.25806451612903225, -0.45161290322580644, 0.20967741935483872]
[-0.3870967741935484, 0.6774193548387096, -0.06451612903225806]
[0.16129032258064516, -0.03225806451612903, -0.3064516129032258]


18
0
-348
-240


Used pictures:
https://www.studypug.com/algebra-help/multiplying-a-matrix-by-another-matrix